version: '3.8'

services:
  server:
    image: server_bb
    build: 
      context: ./BudgetBuddy
      dockerfile: Dockerfile
    ports:
      - "5071:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./.envs/server.env
    depends_on:
        - database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./.envs/db.env
    ports:
      - "1433:1433"
  client:
    image: client_bb
    build:
      context: ./BudgetBuddyUi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    