export const tags = [
  "Food",
  "Groceries",
  "DiningOut",
  "Transportation",
  "Housing",
  "Utilities",
  "Entertainment",
  "Clothing",
  "HealthCare",
  "Education",
  "Electronics",
  "PersonalCare",
  "Travel",
  "Insurance",
  "Income",
  "Gifts",
  "CharitableDonations",
  "PetCare",
  "HomeImprovement",
  "Subscriptions",
  "Other",
];

export const types = ["Income", "Expense"];
