# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        VALID_ISSUER: ${{ secrets.JWTSETTINGS_VALIDISSUER }}
        VALID_AUDIENCE: ${{ secrets.JWTSETTINGS_VALIDAUDIENCE }}
        ISSUER_SIGNING_KEY: ${{ secrets.JWTSETTINGS_ISSUERSIGNINGKEY }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMININFO_ADMINEMAIL }}
      run: dotnet test --no-build --verbosity normal
    
